Leer entrada (1)
Construir ecenario (2)
Calcular el numero de bombas para asignar a cada proceso(3)
Crear procesos ayudantes (4)
Repartir bombas (5)
Calcular Da;os (6)
Recivir resultados de los hijos (7)
Procesar da;os (8)
Imprimir resultado (9)
